name: github_workflow
on:
- push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        output: 'report.txt'
        severity: 'HIGH'
        exit-code: '1'

    # - name: Check Trivy Scan Status
    #   run: exit ${{ steps. trivy-scan.outputs.exit_code }}
    #   continue-on-error: true

    - name: directory
      run: echo "$(ls -l)"

    - name: Send Report to Slack
      if: failure()
      uses: MeilCli/slack-upload-file@v3
      id: report
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
        # text: "$(cat report.txt)"
        # file_type: 'text'
        file_path: 'report.txt'
        #file_name: 'report.txt'
        initial_comment: 'post by ChengXi'

    #- name: Slack Notification
    #  uses: rtCamp/action-slack-notify@v2
    #  env:
    #    SLACK_CHANNEL: general
    #    SLACK_USERNAME: CX23333333
    #    SLACK_COLOR: danger
    #    SLACK_MESSAGE: "Cheng Xi"
    #    SLACK_TITLE: Name
    #    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}


      
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: user/app:latest

    

